### ISSUE TITLE
Backups failing after extended "pause".

### ISSUE THREAD

**Issue by digitalseraphim** [Crypt1-C/Encrypted_-Modpack#62]
Single player world. I tend to walk away for extended periods, and will leave it on the "escape" menu screen. After doing this for a while, I start getting messages to the chat log about "Unable to create backup. Reason: Unable to start new backup as backup is already running". Only way I've found to fix is by completely restarting the client. Searching the logs, I found this related stack trace, though it's possible it is another symptom, not the cause:

```
[15:00:00] [ftbbackups2_Worker-1/ERROR]: Job DEFAULT.ftbbackups2 threw an unhandled Exception: 
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.CompletableFuture$AsyncRun@de2079f rejected from java.util.concurrent.ThreadPoolExecutor@9dd92fb[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 1]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2065) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:833) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1365) ~[?:?]
	at java.util.concurrent.Executors$DelegatedExecutorService.execute(Executors.java:721) ~[?:?]
	at java.util.concurrent.CompletableFuture.asyncRunStage(CompletableFuture.java:1818) ~[?:?]
	at java.util.concurrent.CompletableFuture.runAsync(CompletableFuture.java:2033) ~[?:?]
	at net.creeperhost.ftbbackups.BackupHandler.createBackup(BackupHandler.java:169) ~[ftbbackups2-forge-1.18.2-1.0.13.jar%23181!/:?]
	at net.creeperhost.ftbbackups.BackupHandler.createBackup(BackupHandler.java:139) ~[ftbbackups2-forge-1.18.2-1.0.13.jar%23181!/:?]
	at net.creeperhost.ftbbackups.FTBBackups$BackupJob.execute(FTBBackups.java:132) ~[ftbbackups2-forge-1.18.2-1.0.13.jar%23181!/:?]
	at net.creeperhost.ftbbackups.org.quartz.core.JobRunShell.run(JobRunShell.java:206) [ftbbackups2-forge-1.18.2-1.0.13.jar%23181!/:?]
	at net.creeperhost.ftbbackups.org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:548) [ftbbackups2-forge-1.18.2-1.0.13.jar%23181!/:?]
[15:00:00] [ftbbackups2_Worker-1/ERROR]: Job (DEFAULT.ftbbackups2 threw an exception.
net.creeperhost.ftbbackups.org.quartz.SchedulerException: Job threw an unhandled exception.
	at net.creeperhost.ftbbackups.org.quartz.core.JobRunShell.run(JobRunShell.java:217) [ftbbackups2-forge-1.18.2-1.0.13.jar%23181!/:?]
	at net.creeperhost.ftbbackups.org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:548) [ftbbackups2-forge-1.18.2-1.0.13.jar%23181!/:?]
Caused by: java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.CompletableFuture$AsyncRun@de2079f rejected from java.util.concurrent.ThreadPoolExecutor@9dd92fb[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 1]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2065) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:833) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1365) ~[?:?]
	at java.util.concurrent.Executors$DelegatedExecutorService.execute(Executors.java:721) ~[?:?]
	at java.util.concurrent.CompletableFuture.asyncRunStage(CompletableFuture.java:1818) ~[?:?]
	at java.util.concurrent.CompletableFuture.runAsync(CompletableFuture.java:2033) ~[?:?]
	at net.creeperhost.ftbbackups.BackupHandler.createBackup(BackupHandler.java:169) ~[ftbbackups2-forge-1.18.2-1.0.13.jar%23181!/:?]
	at net.creeperhost.ftbbackups.BackupHandler.createBackup(BackupHandler.java:139) ~[ftbbackups2-forge-1.18.2-1.0.13.jar%23181!/:?]
	at net.creeperhost.ftbbackups.FTBBackups$BackupJob.execute(FTBBackups.java:132) ~[ftbbackups2-forge-1.18.2-1.0.13.jar%23181!/:?]
	at net.creeperhost.ftbbackups.org.quartz.core.JobRunShell.run(JobRunShell.java:206) ~[ftbbackups2-forge-1.18.2-1.0.13.jar%23181!/:?]
	... 1 more
[15:00:27] [Server thread/INFO]: Saving and pausing game...
```

**Comment by djacu** [comment]
I have seen the same "Unable to create backup. Reason: Unable to start new backup as backup is already running". message.

**Comment by Trogdayton** [comment]
I occasionally see this as well, even when I have been actively playing as opposed to leaving it idle. Not just on this pack either, so it might be a bug inherent in a mod.

**Comment by digitalseraphim** [comment]
This is still happening on 1.4
