### ISSUE TITLE
World crashes when running a Marine Fisher

### ISSUE THREAD

**Issue by DasBrain** [Crypt1-C/Encrypted_-Modpack#63]
Problem is an outdated Blood Magic version. See https://github.com/WayofTime/BloodMagic/issues/1918

<pre>
Time: 8/10/22, 6:17 PM
Description: Ticking block entity

java.lang.NullPointerException: Cannot invoke "net.minecraft.world.level.block.state.BlockState.m_60734_()" because the return value of "net.minecraft.world.level.storage.loot.LootContext.m_78953_(net.minecraft.world.level.storage.loot.parameters.LootContextParam)" is null
	at wayoftime.bloodmagic.loot.GlobalLootModifier$VoidingModifier.doApply(GlobalLootModifier.java:319) ~[BloodMagic-1.18.2-3.2.4-39.jar%2380!/:1.18.2-3.2.4-39] {re:classloading}
	at net.minecraftforge.common.loot.LootModifier.apply(LootModifier.java:39) ~[forge-1.18.2-40.1.68-universal.jar%23357!/:?] {re:classloading}
	at net.minecraftforge.common.ForgeHooks.modifyLoot(ForgeHooks.java:1244) ~[forge-1.18.2-40.1.68-universal.jar%23357!/:?] {re:mixin,re:classloading,pl:mixin:APP:lootjs-forge.mixins.json:ForgeHooksMixin,pl:mixin:A}
	at net.minecraft.world.level.storage.loot.LootTable.m_79129_(LootTable.java:89) ~[client-1.18.2-20220404.173914-srg.jar%23352!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at com.buuz135.industrial.block.resourceproduction.tile.MarineFisherTile.work(MarineFisherTile.java:79) ~[industrial-foregoing-1.18.2-3.3.1.4-8.jar%23194!/:3.3.1.4] {re:classloading}
	at com.buuz135.industrial.block.tile.IndustrialWorkingTile.lambda$new$0(IndustrialWorkingTile.java:91) ~[industrial-foregoing-1.18.2-3.3.1.4-8.jar%23194!/:3.3.1.4] {re:classloading}
	at com.hrznstudio.titanium.component.progress.ProgressBarComponent.tickBar(ProgressBarComponent.java:189) ~[titanium-1.18.2-3.5.6-38.jar%23333!/:3.5.6] {re:classloading}
	at com.hrznstudio.titanium.component.progress.MultiProgressBarHandler.update(MultiProgressBarHandler.java:43) ~[titanium-1.18.2-3.5.6-38.jar%23333!/:3.5.6] {re:classloading}
	at com.hrznstudio.titanium.block.tile.ActiveTile.serverTick(ActiveTile.java:238) ~[titanium-1.18.2-3.5.6-38.jar%23333!/:3.5.6] {re:classloading}
	at com.buuz135.industrial.block.tile.IndustrialAreaWorkingTile.serverTick(IndustrialAreaWorkingTile.java:134) ~[industrial-foregoing-1.18.2-3.3.1.4-8.jar%23194!/:3.3.1.4] {re:classloading}
	at com.buuz135.industrial.block.tile.IndustrialAreaWorkingTile.serverTick(IndustrialAreaWorkingTile.java:55) ~[industrial-foregoing-1.18.2-3.3.1.4-8.jar%23194!/:3.3.1.4] {re:classloading}
	at com.hrznstudio.titanium.block.BasicTileBlock.lambda$getTicker$3(BasicTileBlock.java:80) ~[titanium-1.18.2-3.5.6-38.jar%23333!/:3.5.6] {re:classloading}
	at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.m_142224_(LevelChunk.java:673) ~[client-1.18.2-20220404.173914-srg.jar%23352!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.m_142224_(LevelChunk.java:766) ~[client-1.18.2-20220404.173914-srg.jar%23352!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.level.Level.m_46463_(Level.java:476) ~[client-1.18.2-20220404.173914-srg.jar%23352!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:LevelMixin,pl:mixin:APP:mixins.hammerlib.json:LevelMixin,pl:mixin:APP:lootr.mixins.json:MixinLevel,pl:mixin:APP:beyond_earth.mixin.json:BlockSet,pl:mixin:A}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:327) ~[client-1.18.2-20220404.173914-srg.jar%23352!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:supplementaries.mixins.json:ServerLevelMixin,pl:mixin:APP:crafttweaker.mixins.json:common.transform.world.level.MixinServerLevel,pl:mixin:APP:immersiveengineering.mixins.json:coremods.ServerWorldMixin,pl:mixin:APP:byg.mixins.json:common.world.MixinServerLevel,pl:mixin:APP:architects_palette.mixins.json:ServerWorldMixin,pl:mixin:APP:simplerpc.mixins.json:ServerWorldMixin,pl:mixin:APP:create.mixins.json:accessor.ServerLevelAccessor,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:902) ~[client-1.18.2-20220404.173914-srg.jar%23352!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:842) ~[client-1.18.2-20220404.173914-srg.jar%23352!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:84) ~[client-1.18.2-20220404.173914-srg.jar%23352!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:685) ~[client-1.18.2-20220404.173914-srg.jar%23352!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[client-1.18.2-20220404.173914-srg.jar%23352!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) [?:?] {re:mixin}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

&lt;snip&gt;
</pre>

Fix: Update Blood Magic

**Comment by Sedus** [comment]
What do you mean update blood magic? Modpack has the latest 3.2.5-40 version.

**Comment by Sedus** [comment]
Oh 1.3 has 3.2.5-39, 1.4 has 3.2.5-40.
